# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell

      - name: Run a one-line script
        run: | 
          appsToken=$(ruby token.arb "${{ secrets.APPS_KEY }}")
          installToken=$(curl -s -X POST \
            -H "Authorization: Bearer $appsToken" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/app/installations/25054919/access_tokens | jq .token)

          curl -s -X POST \
            -H "Authorization: Bearer $appsToken" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/app/installations/25054919/access_tokens | jq .
          
          echo $installToken

          echo "app_token=$installToken" >> $GITHUB_ENV

      - name: Run a one-line script
        env:
          TOKEN: ${{ env.app_token }}
        run: | 
          echo "testing token output"
          echo $TOKEN
          echo "testing inline $TOKEN"
          echo $token
          echo "end test"

      # - name: Run a one-line script
      #   run: git clone https://x-access-token:ghs_x6QvMtdkSoGx7nDismCkQnlOtnlekW2lkmx3@github.com/christertime/test1.git

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
